name: Deploy production
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set lowercase repo
        run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t ghcr.io/${{ env.REPO }}:latest .
          docker push ghcr.io/${{ env.REPO }}:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set lowercase repo
        run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        env:
          REPO: ${{ env.REPO }}
        with:
          host: 157.180.40.190
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: REPO
          script: |
            echo "Conexión exitosa al VPS"
            docker login ghcr.io -u "ElxCoNe" -p ${{ secrets.TOKEN }}
            docker pull ghcr.io/$REPO:latest
            docker stop prueba-ci-cd || true
            docker rm prueba-ci-cd || true
            docker run -d --name prueba-ci-cd \
                         -p 8085:8080 \
                         ghcr.io/$REPO:latest
